# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('ACHIEVEMENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('SUB_TITLE', models.CharField(max_length=100)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('ISSUER', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PROJECT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('SUBTITLE', models.CharField(max_length=250)),
                ('TYPE', models.CharField(blank=True, max_length=250, null=True)),
                ('IMAGE', models.CharField(blank=True, max_length=100, null=True)),
                ('DESCRIPTION', models.CharField(max_length=5000)),
                ('DATE_START', models.DateTimeField(blank=True, null=True)),
                ('DATE_END', models.DateTimeField(blank=True, null=True)),
                ('STATUS', models.CharField(max_length=100)),
                ('CREATORS', models.CharField(max_length=1000)),
                ('MENTORS', models.CharField(max_length=1000)),
                ('ASSOCIATED_TO', models.CharField(max_length=250)),
                ('STAR_LINK', models.CharField(blank=True, max_length=150, null=True)),
                ('YOUTUBE_LINK', models.CharField(blank=True, max_length=150, null=True)),
                ('GITHUB_APP', models.CharField(blank=True, max_length=150, null=True)),
                ('GITHUB_WEBSITE', models.CharField(blank=True, max_length=150, null=True)),
                ('PLAYSTORE', models.CharField(blank=True, max_length=150, null=True)),
                ('WEBSITE', models.CharField(blank=True, max_length=150, null=True)),
                ('FA_ICON', models.CharField(max_length=50)),
                ('CONTRIBUTION', models.CharField(max_length=1000)),
                ('ASSOCIATED_ACHIEVEMENT', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDiagram',
            fields=[
                ('SKILL_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('CREATIVE_TITLE', models.CharField(max_length=200)),
                ('DATA_WIDTH', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('SKILL_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('SUB_TITLE', models.CharField(max_length=100)),
                ('DESCRIPTION', models.CharField(max_length=500)),
                ('IMAGE', models.CharField(max_length=100)),
            ],
        ),
    ]
