# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='DATE_END',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='DATE_START',
            field=models.DateField(blank=True, null=True),
        ),
    ]
