# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180812_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('TIMELINE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('CONTENT', models.CharField(max_length=5000)),
                ('TIME', models.CharField(blank=True, max_length=100, null=True)),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
