# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingOpportunities',
            fields=[
                ('SPEAKER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('BRIEF', models.CharField(max_length=5000)),
                ('CONTENT', models.CharField(blank=True, max_length=100, null=True)),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
