# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_speakingopportunities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingopportunities',
            name='CATEGORY',
        ),
    ]
