# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_speakingopportunities_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingopportunities',
            name='IMAGE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speakingopportunities',
            name='BRIEF',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='speakingopportunities',
            name='CONTENT',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
